import{_ as o,o as e,c as n,a as t}from"./app-3RcBQnkC.js";const c={},s=t("p",null,"throws、 throw、 try、 catch、 finally",-1),_=t("p",null,"try⽤来指定⼀块预防所有异常的程序；",-1),l=t("p",null,"catch⼦句紧跟在try块后⾯， ⽤来指定你想要捕获的异常的类型；",-1),r=t("p",null,"finally为确保⼀段代码不管发⽣什么异常状况都要被执⾏；",-1),a=t("p",null,"throw语句⽤来明确地抛出⼀个异常；",-1),h=t("p",null,"throws⽤来声明⼀个⽅法可能抛出的各种异常；",-1),i=[s,_,l,r,a,h];function d(u,p){return e(),n("div",null,i)}const y=o(c,[["render",d],["__file","keyword-about-exception.html.vue"]]);export{y as default};
